[project]
name = "lerobot_sim2real"
version = "0.0.1"
description = "Sim2Real Manipulation with LeRobot"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["lerobot==0.3.3", "mani_skill_nightly", "tensorboard", "wandb"]

[project.urls]
Homepage = "https://github.com/StoneT2000/lerobot-sim2real"

[build-system]
requires = ["setuptools>=62.3.0"]
build-backend = "setuptools.build_meta"
